org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
kotlin.code.style=official

GROUP=io.qualtive
POM_ARTIFACT_ID=client
VERSION_NAME=0.1.0-SNAPSHOT

POM_NAME=Qualtive Client
POM_DESCRIPTION=Qualtive Client Library for Android.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/nightshift-habits/qualtive-client-android

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/nightshift-habits/qualtive-client-android
POM_SCM_CONNECTION=scm:git:git://github.com/nightshift-habits/qualtive-client-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/nightshift-habits/qualtive-client-android.git

POM_DEVELOPER_ID=nightshift-habits
POM_DEVELOPER_NAME=Nightshift Habits AB
POM_DEVELOPER_URL=https://qualtive.io

mavenCentralPublishing=true
signAllPublications=true
